### ISSUE TITLE
Can't parse elements whose content is whitespace

### ISSUE THREAD

**Issue by thecabinet** [raku-community-modules/raku-xml#2]
XML can't parse documents where an element contains only whitespace.  In `t/parser.t`, change `$text` to the following; note the `<monkey> </monkey>` element at the end:
`my $text = '<test><title>The title</title><bullocks><item name="first"/><item name="second"/></bullocks><monkey> </monkey></test>';`

Attempting to execute the tests will fail with `could not parse XML`.  I've tried tweaking the `textnode` rule but I don't understand something about grammars well enough to make it work.

**Comment by dwarring** [comment]
Problem no longer seems to exist in latest XML / Rakudo 2020.06.
