### ISSUE TITLE
Using .perl loops forever

### ISSUE THREAD

**Issue by zostay** [raku-community-modules/raku-xml#25]
This might be considered a rakudo bug rather than an exemel bug, but the current built-in `.perl` method does not appear handle circular data well. Running `.per`l on an XML::Node never returns. In the meantime, it might be easy to create a version that outputs something like:

```
from-xml("...")
```

where the `...` is replaced with the stringified representation of the XML::Node. It's not perfect, but at least it would work.

**Comment by supernovus** [comment]
Interesting. I think that is a good suggestion. I'm not actively working on this library right now, but if I have time in the near future, I'll look at implementing that.

**Comment by stmuk** [comment]
This rakudo bug should be fixed now
