### ISSUE TITLE
Flawed logic for method after parameter "offset"

### ISSUE THREAD

**Issue by ZzZombo** [raku-community-modules/raku-xml#52]
https://github.com/supernovus/exemel/blob/b9e209d3f71dee05977da8ad13edb16b377452f8/lib/XML/Element.pm6#L77

Specifying `offset`  of value other than 1 is incompatible with its inner working, as the method is implemented in terms of `before` with offset one greater than the position to insert at, so pretty much is pointless.

**Comment by dwarring** [comment]
@ZzZombo. ^^ that commit shifts the offset by one, which I think makes more sense.

**Comment by supernovus** [comment]
That makes way more sense! I honestly think maybe I should have had before() and after() take no offset parameter at all, and instead had a separate method for inserting a new node at an offset of an existing node. Too late now I guess, don't want to make potentially API breaking changes on a 10 year old library with no idea of how many projects are using it.
